# Generated by Django 4.1.2 on 2022-10-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_beat_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='user',
        ),
    ]
