# Generated by Django 4.1.2 on 2022-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_beat_producers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='url',
        ),
        migrations.AddField(
            model_name='beat',
            name='audio',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
