# Generated by Django 4.1.2 on 2022-10-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_beat_url_beat_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='audio',
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beat')),
            ],
        ),
    ]
