# Generated by Django 4.1.2 on 2022-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_beat_audio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='producers',
            field=models.ManyToManyField(to='main_app.producer'),
        ),
    ]
