# Generated by Django 4.1.2 on 2022-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_beat_producers'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='coverart',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
