# Generated by Django 4.1.2 on 2022-10-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_cover_art_beat_audio_beat_image_delete_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
