# Generated by Django 4.1.2 on 2022-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_beat_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='tiktok',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='twitter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
