# Generated by Django 4.1.2 on 2022-10-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_producer_tiktok_producer_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beat')),
            ],
        ),
    ]
